// Develop a user interface so that a user can type in a prompt for generating a stock report, and the app can go and generate the report for them.
// Things I need
// Chatbox input for user to type prompts 
// Sidebar that lists the previous pdfs that were generated by the chatbox
// A send button to submit the prompt 
// A timer or light up circle thingy that indicates that the generation is currently happening
// A way to connect to the client so that the host has access to the servers we made